### ISSUE TITLE
Does not work wuth Wordpress 5.2.4

### ISSUE THREAD

**Issue by Kamrulhasan12345** [cryptoapi/Give-Wordpress-Donations-Bitcoin#2]
I tested this on wp 5.2.4 and it did not work. It shows this error everywhere:
![Screenshot_20191027-092318](https://user-images.githubusercontent.com/32530625/67629111-82ba1b00-f869-11e9-9e5b-d949ae821795.png)

**Comment by cryptoapi** [comment]
Fixed
